'use strict';
const $=id=>document.getElementById(id);
let token='',mode='qr',queuePaused=false,cursor=0,refreshing=false,toastTimer,pendingSend=null;
const labels={connected:'Conectado',disconnected:'Desconectado',connecting:'Reconectando',pairing:'Pareando',paused:'Pausado',queued:'Na fila',sending:'Enviando',sent:'Enviado ao servidor',delivered:'Entregue',read:'Lida',uncertain:'Resultado incerto',failed:'Falhou',cancelled:'Cancelada'};
function toast(message,error=false){$('toast').textContent=message;$('toast').className=error?'error':'';$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,9000)}
async function api(path,body,extra={}){let response;try{response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'}),...extra},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(48000)})}catch{throw new Error('Falha de rede. Para envio, tente novamente sem alterar os campos: a chave será preservada.')};const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível concluir a operação');return data}
function td(text){const el=document.createElement('td');el.textContent=text;return el}
function showConnection(c){$('state').textContent=labels[c.state]||c.state;$('state-detail').textContent=c.detail;const qr=c.qr&&c.expires>Date.now()/1000&&!c.code;const code=c.code&&c.expires>Date.now()/1000;$('qr').hidden=!qr;if(qr)$('qr').src=c.qr;else $('qr').removeAttribute('src');$('pair-code').hidden=!code;$('pair-code').textContent=code||'';$('pair-placeholder').hidden=!!(qr||code);$('pair-expiry').textContent=(qr||code)?'Atualização do pareamento em '+Math.max(0,Math.floor(c.expires-Date.now()/1000))+' s':''}
async function refresh(){if(!token||refreshing)return;refreshing=true;try{const [s,m,counts]=await Promise.all([api('/status'),api('/messages'),api('/metrics')]);showConnection(s.connection);queuePaused=s.queue_paused;$('pause-queue').textContent=queuePaused?'Retomar fila':'Pausar fila';$('queued').textContent=counts.queued||0;$('delivered').textContent=(counts.delivered||0)+(counts.read||0);$('attention').textContent=(counts.uncertain||0)+(counts.failed||0);$('cadence').textContent=`Um envio a cada ${s.interval_seconds} segundos. ${queuePaused?'Fila pausada.':'Fila ativa.'}`;$('hook-label').textContent=s.webhook_enabled?'Webhook configurado':'Eventos locais';$('messages').replaceChildren();$('empty').hidden=m.length>0;for(const x of m){const tr=document.createElement('tr');tr.append(td(x.to),td(x.kind));const state=td('');const badge=document.createElement('span');badge.className='badge '+x.status;badge.textContent=labels[x.status]||x.status;badge.title=x.error||x.id;state.append(badge);tr.append(state,td(new Date(x.created*1000).toLocaleString('pt-BR')));const action=td('');if(x.status==='queued'){const b=document.createElement('button');b.textContent='Cancelar';b.className='secondary row-action';b.onclick=async()=>{try{await api('/messages/'+x.id+'/cancel',{});await refresh()}catch(e){toast(e.message,true)}};action.append(b)}else{action.textContent=x.id.slice(0,8);action.title=x.error||x.id}tr.append(action);$('messages').append(tr)}$('refresh-time').textContent='Atualizado às '+new Date().toLocaleTimeString('pt-BR')}catch(e){toast(e.message,true)}finally{refreshing=false}}
async function loadEvents(){const events=await api('/events?after='+cursor);for(const e of events){cursor=Math.max(cursor,e.seq);const row=document.createElement('div');row.className='event';const content=document.createElement('div');const title=document.createElement('strong');title.textContent=e.type;const p=document.createElement('p');p.textContent=e.data.text||e.data.detail||e.data.error||e.data.action||e.data.chat||e.data.id||JSON.stringify(e.data);const small=document.createElement('small');small.textContent=new Date(e.created*1000).toLocaleString('pt-BR')+' · '+e.delivery;content.append(title,p);row.append(content,small);if(e.delivery==='dead'){const b=document.createElement('button');b.className='secondary row-action';b.textContent='Repetir webhook';b.onclick=async()=>{try{await api('/events/'+e.id+'/retry',{});toast('Webhook colocado novamente na fila.');b.disabled=true}catch(err){toast(err.message,true)}};row.append(b)}$('events').prepend(row)}while($('events').children.length>100)$('events').lastChild.remove()}
$('login-form').onsubmit=async e=>{e.preventDefault();token=$('token').value.trim();try{await api('/status');$('token').value='';$('login').hidden=true;$('app').hidden=false;$('logout').hidden=false;await refresh();await loadEvents()}catch(err){token='';toast(err.message,true)}};
$('logout').onclick=()=>{token='';pendingSend=null;location.reload()};
function choose(m){mode=m;$('mode-qr').classList.toggle('selected',m==='qr');$('mode-phone').classList.toggle('selected',m==='phone');$('phone-field').hidden=m!=='phone';$('pair-phone').required=m==='phone';$('connect-button').firstChild.textContent=m==='qr'?'Gerar QR Code ':'Gerar código ';$('connect-help').textContent=m==='qr'?'No celular: Dispositivos conectados → Conectar dispositivo. Escaneie o QR Code.':'No celular: Dispositivos conectados → Conectar dispositivo → Conectar com número de telefone. Digite o código mostrado aqui.'}
$('mode-qr').onclick=()=>choose('qr');$('mode-phone').onclick=()=>choose('phone');
$('connect-form').onsubmit=async e=>{e.preventDefault();$('connect-button').disabled=true;try{const s=await api('/connection/connect',{phone:mode==='phone'?$('pair-phone').value.trim():''});showConnection(s);toast('Solicitação de conexão concluída.')}catch(err){toast(err.message,true)}finally{$('connect-button').disabled=false}};
$('disconnect').onclick=async()=>{try{await api('/connection/pause',{});await refresh()}catch(e){toast(e.message,true)}};
$('pause-queue').onclick=async()=>{try{await api('/queue',{paused:!queuePaused});await refresh()}catch(e){toast(e.message,true)}};
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
$('send-form').onsubmit=async e=>{e.preventDefault();$('send-button').disabled=true;try{const p={to:$('to').value.trim(),kind:'text',text:$('text').value};const f=$('file').files[0];if(f){if(f.size>16*1024*1024)throw new Error('O limite é 16 MiB.');const ext=f.name.split('.').pop().toLowerCase();const types={jpg:['image','image/jpeg'],jpeg:['image','image/jpeg'],png:['image','image/png'],pdf:['document','application/pdf'],txt:['document','text/plain'],mp4:['video','video/mp4'],mp3:['audio','audio/mpeg'],ogg:['audio','audio/ogg'],m4a:['audio','audio/mp4']};if(!types[ext])throw new Error('Formato não suportado.');[p.kind,p.mime]=types[ext];p.filename=f.name;p.data=await fileData(f)}else if(!p.text.trim())throw new Error('Escreva uma mensagem ou selecione um arquivo.');const fingerprint=JSON.stringify(p);if(!pendingSend||pendingSend.fingerprint!==fingerprint)pendingSend={key:crypto.randomUUID(),fingerprint};const m=await api('/messages',p,{'Idempotency-Key':pendingSend.key});pendingSend=null;$('text').value='';$('file').value='';toast('Mensagem registrada: '+m.id.slice(0,8));await refresh()}catch(err){toast(err.message,true)}finally{$('send-button').disabled=false}};
$('refresh').onclick=refresh;$('more-events').onclick=()=>loadEvents().catch(e=>toast(e.message,true));setInterval(()=>{if(!document.hidden)refresh()},5000);
